REQUEST_ID=req-001-sample-training

WORKLOAD_TYPE=sagemaker-training
CONTAINER_IMAGE=python:3.11-slim

PACKAGE_MANAGER=pip
ARTIFACTORY_REPO=pypi-certified

# Optional:
# PYTHON_COMMAND=python

# Optional for PACKAGE_MANAGER=conda
# CONDA_ENV_NAME=base
